### ISSUE TITLE
cybermon-bigquery

### ISSUE THREAD

**Issue by hossamsamy007** [cybermaggedon/cyberprobe#20]
File "/usr/local/bin/cybermon-bigquery", line 78, in <module>
    scopes=scopes)
  File "/usr/local/lib/python2.7/dist-packages/oauth2client/service_account.py", line 219, in from_json_keyfile_name
    with open(filename, 'r') as file_obj:
IOError: [Errno 2] No such file or directory: '/etc/cyberprobe/private.json'

**Comment by cybermaggedon** [comment]
You have to supply /etc/cyberprobe/private.json yourself if you want to use BigQuery - it's a key you get from the Google platform.

To set up, you need to set up a Google Cloud project.  Next step is probably to follow Google's BigQuery quickstart to get yourself up and running.  BigQuery is a charged service, but low cost, I think you can get free credits as a first time user.

Once you're running with BIgQuery, you need to create a service account in the IAM to allow you to connect.  When creating the account, make sure it's an API, not a user account, and make sure to collect a JSON key.  This is the file you store at /etc/cyberprobe/private.json

Finally, the service account needs access to BigQuery in the IAM system.  If you're just playing around, you can give it Project Owner permissions to be a superuser, otherwise you'll need to read up on roles etc.

**Comment by hossamsamy007** [comment]
i made setting up to google cloud project and then we made aGoogle's
BigQuery quickstart  and it is runnig  and itis free  what is the next step
i dont understand i sent you the step am in it now

**Comment by cybermaggedon** [comment]
You need to set up a Service Account user under Google Cloud.  That's under IAM & admin > Service Accounts. Give the account a name, set the role to BigQuery Admin.  Tick Furnish a new private key.  Select JSON. Click Create.  You then download the key file.

Once you have the key file, that can be used with `cybermon-bigquery` by putting the key file in `/etc/cyberprobe/private.json`.  Alternatively you can specify the name e.g.
```
cybermon-bigquery tcp://localhost:5555 name-of-key.json
```

**Comment by cybermaggedon** [comment]
You also need to create a dataset in BigQuery, and give the service account access.  You need the service account's ID, which you just created.  You can see it in the IAM dialogue on the Google Cloud console, or you can see it in the JSON file you just downloaded.  The ID looks like an email address which looks like NAME@PROJECT.iam.gserviceaccount.com.

On the BigQuery display in the datasets viewer on the right, you can add the dataset.  Call it `cyberprobe`. You also need to share the dataset with the user you just created, so select the menu on your dataset, and select Share.  Put your service account user in the dialogue and let it be admin for the dataset.

You should be all set to go now.
