### ISSUE TITLE
the visualization steps please

### ISSUE THREAD

**Issue by hossamsamy007** [cybermaggedon/cyberprobe#24]
1-the new version of elastic-search doesn't support ttl version 2.3.5 does how you will  update that in the new version since the old versions are ugly very much.
2-https-server in the visualization what does it means 

3-Dns -QUERY HOW CAN I GET IT 

4-the packets bring to me ipv4:192.222.1.50  , i dont want to show ipv4 in the kibana please answer my questions

**Comment by cybermaggedon** [comment]
Fixed that for you - the latest cyberprobe (f13aaa7eb0756a7f6c452aaa9efe42a59ecda46b) uses ElasticSearch API without TTL. I have it working with ElasticSearch 5.6.5 and Kibana 5.6.  It's currently going through GoCD build, will be released in about 30 minutes.

There's some other things not working with the ElasticSearch loader, will a look.

**Comment by cybermaggedon** [comment]
1 and 3) are fixed in 49cd43484d0c5c60c769ad6e4aeacac8889619aa

Once loaded, you can query for dns_message actions thus..

`curl -s -XPOST "http://localhost:9200/cyberprobe/observation/_search?pretty=true" -d '{"query": {"term": {"action": "dns_message"}}}'`

**Comment by cybermaggedon** [comment]
I don't know what you mean by https-server...?  Can you explain?

You don't have to expose ipv4 if you don't want to.  But you need to do a bit of reading about how to use ElasticSearch...

e.g. you can use query source fields to decide what fields to return in a query... https://www.elastic.co/guide/en/elasticsearch/reference/2.3/search-request-source-filtering.html

curl -s -XPOST "http://localhost:9200/cyberprobe/observation/_search?pretty=true" -d '{"_source":{"include":["device","time"]}, "query": {"term": {"action": "dns_message"}}}'

You might also want to play with the provided db.lua file and change the mapping so that IP addresses are not stored if you don't want them.

**Comment by cybermaggedon** [comment]
Latest Kibana and ElasticSearch deployable in containers here...

http://cyberprobe.trustnetworks.com/cyberprobe.html#A-containerised-processing-system
