### ISSUE TITLE
Getting error of UUID4 for EleasticSearch 

### ISSUE THREAD

**Issue by khudabux** [cybermaggedon/cyberprobe#29]
Hello,

I am getting an error of UUID4 for eleasticSearch script. I have installed Cyberpprobe 1.6.0, NODEJS v6, Node v3, and ELK 6.1.1 on Ubuntu 16.04. I need your help in this regard to fix it.

Thanks.

**Comment by cybermaggedon** [comment]
Thanks for raising this.  There have been a couple of recent changes that will be useful to you.

Firstly, there was a bug which could cause UUID generation to re-use UUIDs, which was fixed in cyberprobe 1.6.7.  Secondly, cyberprobe has a few areas of unmaintained code which was causing problems for people, and one of the areas was the ElasticSearch loader. The ElasticSearch mapping didn't work with ES 6.1.1.

As a result, I have deprecated the ElasticSearch Lua code in favour of the pub/sub module which I have brought up to date, so that it loads many more fields.  IOC information and GeoIP information is searchable now. I've been tidying up things a little bit and version 1.7.4 was pushed to GitHub release, and Docker hub today: https://github.com/cybermaggedon/cyberprobe/releases

You may be interested in using cyberprobe in containerised form, which is an easy way to launch cyberprobe with ElasticSearch:

http://cyberprobe.trustnetworks.com/cyberprobe.html#A-containerised-processing-system

or you can read the documentation on the updated ElasticSearch loader:

http://cyberprobe.trustnetworks.com/cyberprobe.html#cybermon_002delasticsearch-invocation

I have this working fine with ElasticSearch/Kibana 6.1.1.  There is a Dashboard that works with Kibana here:

https://github.com/cybermaggedon/cyberprobe.trustnetworks.com/blob/master/kibana-dashboards.json

**Comment by cybermaggedon** [comment]
Opened a discussion forum if you want to discuss this further...
https://groups.google.com/d/forum/cyberprobe-discussion
